TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
#DB += xxx.db
DB_INSTALLS += $(ASYN)/db/asynRecord.db
DB_INSTALLS += $(TOP)/serialTestApp/Db/TPG366/TPG366.subs
DB_INSTALLS += $(TOP)/serialTestApp/Db/TPG366/TPG366.db
DB_INSTALLS += $(TOP)/serialTestApp/Db/TPG366/TPG366.proto
DB_INSTALLS += $(TOP)/serialTestApp/Db/TC400/TC400.db
DB_INSTALLS += $(TOP)/serialTestApp/Db/TC400/TC400.proto
DB_INSTALLS += $(TOP)/serialTestApp/Db/OBC/OBC.db
DB_INSTALLS += $(TOP)/serialTestApp/Db/OBC/OBC.proto
DB_INSTALLS += $(TOP)/serialTestApp/Db/ACP40/ACP40.db
DB_INSTALLS += $(TOP)/serialTestApp/Db/ACP40/ACP40.proto
DB_INSTALLS += $(TOP)/serialTestApp/Db/ACP40/ACP40.subs
DB_INSTALLS += $(TOP)/serialTestApp/Db/A100L/A100L.db
DB_INSTALLS += $(TOP)/serialTestApp/Db/A100L/A100L.subs
DB_INSTALLS += $(TOP)/serialTestApp/Db/A100L/A100L.proto
DB_INSTALLS += $(TOP)/serialTestApp/Db/OsakaPump/OsakaPump.db
DB_INSTALLS += $(TOP)/serialTestApp/Db/OsakaPump/OsakaPump.proto
DB_INSTALLS += $(TOP)/serialTestApp/Db/PSC232/PSC232.db
DB_INSTALLS += $(TOP)/serialTestApp/Db/PSC232/PSC232.proto
DB_INSTALLS += $(TOP)/serialTestApp/Db/PSC232/PSC232.subs
DB_INSTALLS += $(TOP)/serialTestApp/Db/SM15K/SM15K.db
DB_INSTALLS += $(TOP)/serialTestApp/Db/SM15K/SM15K.proto
DB_INSTALLS += $(TOP)/serialTestApp/Db/SM15K/SM15K.subs
DB_INSTALLS += $(TOP)/serialTestApp/Db/ET/ET.db
DB_INSTALLS += $(TOP)/serialTestApp/Db/ET/ET.proto
DB_INSTALLS += $(TOP)/serialTestApp/Db/ET/ET.subs
#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE


